package ch.unizh.ori.cruciverbalismus;

public class DefaultLexiconString {
	
	public static final String LEX_STRING = 
		"cantare\tsingen\n"
		+"ridere\tlachen, auslachen\n"
		+"et\tund, auch\n"
		+"clamare\tschreien, rufen\n"
		+"ululare\theulen, jaulen\n"
		+"tacere\tschweigen, verschweigen\n"
		+"noniam\tnicht mehr\n"
		+"autem\taber, jedoch\n"
		+"atque\tund\n"
		+"ac\tund\n"
		+"vocare\trufen, nennen\n"
		+"non\tnicht\n"
		+"iam\tschon, bereits\n"
		+"venire\tkommen\n"
		+"dicere\tsagen, sprechen\n"
		+"quis\twer?\n"
		+"sed\taber, sondern\n"
		+"maledicere\tschimpfen\n"
		+"semper\timmer, stets\n"
		+"deinde\tvon da an, darauf, ferner\n"
		+"decet\tes gehört sich, es passt\n"
		+"neque\tund nicht, auch nicht, aber nicht\n"
		+"nec\tund nicht, auch nicht, aber nicht\n"
		+"tandem\tendlich, schliesslich\n"
		+"ludere\tspielen, scherzen\n"
		+"ubi\two?\n"
		+"esse\tsein\n"
		+"dominus\t(Haus-)Herr\n"
		+"domina\tHerrin\n"
		+"vilicus\t(Guts-)Verwalter\n"
		+"servus\tSklave\n"
		+"serva\tSklavin\n"
		+"libertus\tFreigelassener\n"
		+"liberta\tFreigelassene\n"
		+"tum\tdamals; dann, da\n"
		+"caelum\tHimmel\n"
		+"obscurus\tdunkel\n"
		+"que\tund\n"
		+"cur\twarum? weshalb?\n"
		+"laborare\tsich anstrengen, streng arbeiten\n"
		+"subito\tplötzlich\n"
		+"quietus\truhig\n"
		+"plaustrum\t(Last-)Karren, Wagen\n"
		+"frumentum\tGetreide\n"
		+"enim\tdenn, nämlich\n"
		+"maturus\treif; rechtzeitig\n"
		+"quoque\tauch\n"
		+"puella\tMädchen\n"
		+"ecce!\tda! sieh mal!\n"
		+"etiam\tauch, noch, sogar\n"
		+"onustus,\tbeladen, bepackt\n"
		+"defessu\tmüde, erschöpft\n"
		+"iterum\tzum zweiten Mal, wiederum\n"
		+"cuncti\talle\n"
		+"laetus\tfröhlich, vergnügt\n"
		+"salvus\twohlbehalten, unversehrt\n"
		+"secundus\tzweiter; günstig\n"
		+"interrogare\tfragen\n"
		+"quid\twas?\n"
		+"quem\twen?\n"
		+"quaerere\tsuchen, (fragen)\n"
		+"audire\thören\n"
		+"videre\tsehen, besichtigen, besuchen\n"
		+"complere\tfüllen\n"
		+"aut\toder\n"
		+"portare\ttragen, bringen\n"
		+"apportare\therbeitragen, herbringen\n"
		+"onerare\tbeladen\n"
		+"deesse\tfehlen, mangeln\n"
		+"currere\tlaufen, eilen\n"
		+"posse\tkönnen\n"
		+"haerere\tfesthängen, hängenbleiben\n"
		+"itaque\tdeshalb, daher\n"
		+"nondum\tnoch nicht\n"
		+"adesse\tdasein\n"
		+"rota\tRad\n"
		+"petere\t(etw.) verlangen, (er-)bitten; (jd.) aufsuchen, etw. aufsuchen\n"
		+"rotampetit\ter verlangt ein Rad\n"
		+"dominumpetit\ter sucht den Herren auf\n"
		+"villampetunt\tsie suchen das Landhaus auf, sie begeben sich zum Landhaus\n"
		+"stultus\tdumm, töricht\n"
		+"nominare\t(be)nennen\n"
		+"mittere\tschicken, gehen lassen\n"
		+"dimittere\taus-, los-, wegschicken; entlassen\n"
		+"regere\tlenken, leiten\n"
		+"incitare\tantreiben, reizen\n"
		+"nam\tdenn, nämlich\n"
		+"damnum\tSchaden\n"
		+"spectare\t(an)schauen, betrachten\n"
		+"prope\tnahe, in der Nähe\n"
		+"statim\tsofort, auf der Stelle\n"
		+"iuvare\tunterstützen, helfen\n"
		+"servumiuvant\tsie helfen dem Sklaven\n"
		+"mehercule\tbeim Herkules!, wahrhaftig\n"
		+"instrumentum\tWerkzeug, Hilfsmittel\n"
		+"villa\tLandhaus, Landgut\n"
		+"volare\tfliegen, eilen\n"
		+"avolare\twegfliegen, enteilen, loslaufen\n"
		+"diu\tlange (Zeit)\n"
		+"exspectare\tausschauen, erwarten\n"
		+"iratus\tzornig, erzürnt\n"
		+"nunc\tnun, jetzt\n"
		+"asinus\tEsel\n"
		+"verberare\tschlagen\n"
		+"ceteri\tdie Übrigen\n"
		+"tertius\tdritter\n"
		+"excitare\taufscheuchen, wecken\n"
		+"negotium\tGeschäft, Aufgabe\n"
		+"dare\tgeben\n"
		+"aqua\tWasser\n"
		+"adesse\thelfen\n"
		+"Selenus domino adest\tSelenus hilft dem Herrn\n"
		+"imperium\tBefehl, Herrschaft, Reich, Machtbereich\n"
		+"iucundus\tangenehm, erfreulich, interessant\n"
		+"tamen\tdennoch, doch\n"
		+"parere\terscheinen, gehorchen, gehorsam sein\n"
		+"cui\twem?\n"
		+"imperare\tbefehlen, herrschen über, einen Auftrag erteilen\n"
		+"dominusservisimperat\tder Herr gibt den Sklaven Aufträge\n"
		+"romanipopulisimperant\tdie Römer herrschen über die Völker\n"
		+"parare\tvorbereiten,bereiten\n"
		+"libenter\tgern, mit Vergnügen\n"
		+"liberi\tKinder\n"
		+"magister\tLehrer, Leiter\n"
		+"docere\tlehren, unterrichten\n"
		+"magisterliberoselementadocet\tder Lehrer bringt den Kindern das Alphabet bei\n"
		+"ludus\tSpiel; Schule, Unterricht\n"
		+"interesse\tteilnehmen\n"
		+"liberiludointersunt\tdie Kinder nehmen am unterricht teil\n"
		+"vicinus\tNachbar\n"
		+"sicut\tgleich wie\n"
		+"littera\tBuchstabe\n"
		+"litterae\tBrief; Literatur; Wissenschaft(en)\n"
		+"scribere\tschreiben\n"
		+"puer\tJunge, Kind\n"
		+"monstrare\tzeigen\n"
		+"hodie\theute\n"
		+"vituperare\ttadeln\n"
		+"laudare\tloben, rühmen\n"
		+"prämium\tBelohnung\n"
		+"verbum\tWort\n"
		+"legere\tsammeln, auswählen, lesen\n"
		+"liber\tBuch\n"
		+"donare\tschenken\n"
		+"pulcher\tschön, herrlich\n"
		+"gaudium\tFreude, Vergnügen\n"
		+"miser\tunglücklich\n"
		+"liber\tfrei, unabhängig\n"
		+"saepe\toft\n"
		+"vita\tLeben\n"
		+"timere\tfürchten, sich fürchten\n"
		+"discipulus\tSchüler\n"
		+"etet\tsowohl ... als auch ...\n"
		+"lingua\tZunge, Sprache\n"
		+"discere\tlernen\n"
		+"salutare\t(be)grüssen\n"
		+"primum\tzuerst, zum ersten Mal\n"
		+"repetere\twiederhohlen, zurückfordern; zurückgehen\n"
		+"declamare\tlaut vortragen\n"
		+"contentus\tzufrieden\n"
		+"attentus\taufmerksam\n"
		+"signum\tZeichen\n"
		+"posrtemo\tzuletzt, schliesslich\n"
		+"dictum\tSprichwort, Äuserung\n"
		+"dictare\tdiktieren\n"
		+"schola\tSchule\n"
		+"sic\tso\n"
		+"finire\tbegrenzen, beenden\n"
		+"quartus\tvierter\n"
		+"capere\tfassen, nehmen, ergreifen\n"
		+"cupere\twünschen, begehren\n"
		+"forte\tzufällig\n"
		+"amicus\tFreund, Freundin; befreundet\n"
		+"vos\tihr\n"
		+"occupatus\tbeschäftigt\n"
		+"nihil\tnichts\n"
		+"nil\tnichts\n"
		+"ego\tich\n"
		+"nonne\t... denn nicht?, ... etwa nicht?, ... doch?\n"
		+"tu\tdu\n"
		+"inesse\tdarin sein, enthalten sein\n"
		+"frumentumsaccoinest\tdas Getreide ist im Sack\n"
		+"ne\tFragepartikel am ersten Wort angehängt; bleibt unübersetzt\n"
		+"multi\tviele, zahlreiche\n"
		+"licet\tes ist erlaubt\n"
		+"terrere\t(er)schrecken\n"
		+"terreoamicum\tich erschrecke den Freund\n"
		+"diligere\tlieben, hochschätzen\n"
		+"num\t... etwa?\n"
		+"proinde\tdaher, also (auffordernd)\n"
		+"nos\twir\n"
		+"adiuvare\tunterstützen, helfen\n"
		+"adiuvamusamicos\twir helfen den Freunden\n"
		+"quomodo\tauf welche Weise? wie?\n"
		+"intrare\teintreten, betreten\n"
		+"aureliaintratvillam\tA. betritt das Haus\n"
		+"vel\toder\n"
		+"improbus\tböse, frech\n"
		+"probus\ttüchtig, rechtschaffen, brav\n"
		+"certe\tsicher, gewiss\n"
		+"illudere\tjd. einen Streich spielen, jd. verspotten\n"
		+"curilluditislamprisco\tWarum spielt ihr dem Lampriscus einen Streich?\n"
		+"causa\tUrsache, Grund; Vorfall, Streitsache\n"
		+"facere\ttun, machen\n"
		+"severus\tstreng, ernst\n"
		+"debere\tschulden: müssen, sollen\n"
		+"numquam\tniemals, nie\n"
		+"nonnumquam\tmanchmal, gelegentlich\n"
		+"studere\tsich bemühen um, sich beschäftigen mit, streben nach\n"
		+"studeogeometriae\tich beschäftige mich mit der Geometrie\n"
		+"intellegere\teinsehen, verstehen\n"
		+"populus\tVolk\n"
		+"quidem\tzwar, wenigstens; gewiss, freilich\n"
		+"doctus\tgelehrt, gebildet\n"
		+"studium\tEifer, Bemühung, (wissenschaftl.) Betätigung\n"
		+"necessarius\tnotwendig; verwandt\n"
		+"natare\tschwimmen\n"
		+"nequeneque\tweder ... noch ...\n"
		+"scire\twissen, verstehen\n"
		+"ignavus\tfeige, träge\n"
		+"quintus\tfünfter\n"
		+"vinum\tWein\n"
		+"tuus\tdein\n"
		+"quam\twie\n"
		+"habere\thaben, halten\n"
		+"tradere\tüberliefern, übergeben\n"
		+"vicinus\tNachbar; benachbart\n"
		+"inquit\tsagt er/sie/es\n"
		+"noster\tunser\n"
		+"reperire\tfinden\n"
		+"alienus\tfremd, nicht zugehörig\n"
		+"tectum\tDach\n"
		+"longinquus\tweit entfernt\n"
		+"cuius\twessen?\n"
		+"meus\tmein\n"
		+"murus\tMauer\n"
		+"aedificium\tGebäude\n"
		+"tantus\tso gross, so viel\n"
		+"at\taber, dagegen\n"
		+"magnus\tgross, bedeutend\n"
		+"numerus\tZahl; Menge\n"
		+"tam\tso, so sehr\n"
		+"superbus\tstolz, überheblich, prächtig\n"
		+"nemo\tniemand\n"
		+"salvere\tgesund sein\n"
		+"salve\tsei gegrüsst! Guten Tag!\n"
		+"salvete\tseid gegrüsst! Guten Tag!\n"
		+"vester\teuer\n"
		+"abesse\tabwesend sein, entfernt sein; fehlen\n"
		+"accipere\tannehmen, ampfangen, aufnehmen\n"
		+"avaritia\tHabgier, Geiz\n"
		+"tenere\thalten, festhalten\n"
		+"conviva\t(zum Essen geladener) Gast\n"
		+"hora\tStunde\n"
		+"cena\t(Haupt-)Mahlzeit\n"
		+"nonnulli\tmanche, einige\n"
		+"ibi\tda, dort\n"
		+"clam\theimlich\n"
		+"vero\taber, freilich\n"
		+"bonus\tgut, tüchtig\n"
		+"gaudere\tsich freuen\n"
		+"gratia\tGunst, Zuneigung; Ansehen; Dank; Anmut\n"
		+"agere\ttreiben, betreiben, handeln; tun\n"
		+"gratiasagere\tdanken, Dank sagen\n"
		+"apparere\terscheinen, sich zeigen\n"
		+"hic\thier\n"
		+"vacuus\tleer, frei\n"
		+"carus\tlieb, teuer\n"
		+"rarus\tselten, rar\n"
		+"sedulus\tfleissig, eifrig\n"
		+"piger\tfaul, träge\n"
		+"unus\tein einziger, einer";

}
