
package ch.unizh.ori.nabu.ui.swing.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "NabuWS", targetNamespace = "http://webservices.http.ui.nabu.ori.unizh.ch/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NabuWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ch.unizh.ori.nabu.ui.swing.webservice.StringArray>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVocs", targetNamespace = "http://webservices.http.ui.nabu.ori.unizh.ch/", className = "ch.unizh.ori.nabu.ui.swing.webservice.GetVocs")
    @ResponseWrapper(localName = "getVocsResponse", targetNamespace = "http://webservices.http.ui.nabu.ori.unizh.ch/", className = "ch.unizh.ori.nabu.ui.swing.webservice.GetVocsResponse")
    public List<StringArray> getVocs(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSubs", targetNamespace = "http://webservices.http.ui.nabu.ori.unizh.ch/", className = "ch.unizh.ori.nabu.ui.swing.webservice.GetSubs")
    @ResponseWrapper(localName = "getSubsResponse", targetNamespace = "http://webservices.http.ui.nabu.ori.unizh.ch/", className = "ch.unizh.ori.nabu.ui.swing.webservice.GetSubsResponse")
    public List<String> getSubs();

}
