
package ch.unizh.ori.nabu.ui.swing.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "NabuWSService", targetNamespace = "http://webservices.http.ui.nabu.ori.unizh.ch/", wsdlLocation = "http://localhost:8080/nabu/NabuWS?wsdl")
public class NabuWSService
    extends Service
{

    private final static URL NABUWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ch.unizh.ori.nabu.ui.swing.webservice.NabuWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ch.unizh.ori.nabu.ui.swing.webservice.NabuWSService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/nabu/NabuWS?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/nabu/NabuWS?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        NABUWSSERVICE_WSDL_LOCATION = url;
    }

    public NabuWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NabuWSService() {
        super(NABUWSSERVICE_WSDL_LOCATION, new QName("http://webservices.http.ui.nabu.ori.unizh.ch/", "NabuWSService"));
    }

    /**
     * 
     * @return
     *     returns NabuWS
     */
    @WebEndpoint(name = "NabuWSPort")
    public NabuWS getNabuWSPort() {
        return super.getPort(new QName("http://webservices.http.ui.nabu.ori.unizh.ch/", "NabuWSPort"), NabuWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NabuWS
     */
    @WebEndpoint(name = "NabuWSPort")
    public NabuWS getNabuWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.http.ui.nabu.ori.unizh.ch/", "NabuWSPort"), NabuWS.class, features);
    }

}
